import { test, expect } from '@playwright/test';
test('Image Service real API flow: private listing, folders, upload, copy URL, rename and delete', async ({ page, context }) => {
  const errors:string[]=[]; page.on('pageerror',e=>errors.push(e.message));
  const base='http://127.0.0.1:4314';
  await page.goto(base+'/manage');
  await expect(page.getByText('Pro správu obrázků se přihlas povoleným Discord účtem.')).toBeVisible();
  expect((await context.request.get(base+'/api/media')).status()).toBe(401);
  const start=await context.request.get(base+'/auth/discord',{maxRedirects:0});
  const state=new URL(start.headers().location).searchParams.get('state');
  await context.request.get(`${base}/auth/discord/callback?code=fixture&state=${state}`,{maxRedirects:0});
  await page.reload();
  await expect(page.getByRole('region',{name:'Media library'})).toBeVisible();
  await page.getByRole('button',{name:'Nová složka'}).click();
  await page.getByLabel('Destination').fill('test/food');
  await page.getByRole('button',{name:'Uložit',exact:true}).click();
  await expect(page.getByRole('dialog')).toHaveCount(0);
  await page.locator('.media-entry').filter({hasText:'test'}).dblclick();
  await page.locator('.media-entry').filter({hasText:'food'}).dblclick();
  await page.getByLabel('Upload images').setInputFiles('public/diamondcrew-logo.png');
  await page.getByRole('button',{name:'Nahrát obrázky',exact:true}).click();
  await expect(page.getByLabel('Public URL')).toHaveValue('https://img.dcrp.cz/test/food/diamondcrew-logo.png');
  await context.grantPermissions(['clipboard-read','clipboard-write']);
  await page.getByRole('button',{name:'COPY URL',exact:true}).click();
  expect(await page.evaluate(()=>navigator.clipboard.readText())).toBe('https://img.dcrp.cz/test/food/diamondcrew-logo.png');
  await page.getByRole('button',{name:'Přejmenovat',exact:true}).click();
  await page.getByLabel('Destination').fill('renamed.png');
  await page.getByRole('button',{name:'Uložit',exact:true}).click();
  await expect(page.getByRole('dialog')).toHaveCount(0);
  await page.locator('.media-entry').filter({hasText:'renamed.png'}).click();
  await page.getByRole('button',{name:'Smazat',exact:true}).click();
  await page.getByRole('dialog').getByRole('button',{name:'Smazat',exact:true}).click();
  await expect(page.locator('.media-entry').filter({hasText:'renamed.png'})).toHaveCount(0);
  await page.getByRole('navigation',{name:'Media folders'}).getByRole('button',{name:'Media',exact:true}).click();
  await page.locator('.media-entry').filter({hasText:'projects'}).dblclick();
  await page.locator('.media-entry').filter({hasText:'diamondcrew.png'}).click();
  await page.setViewportSize({width:1440,height:1000});
  await expect(page.locator('.preview img')).toBeVisible();
  await page.screenshot({path:'.artifacts/image-service-management.png',fullPage:true});
  await page.setViewportSize({width:390,height:844});
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
  await page.screenshot({path:'.artifacts/image-service-mobile.png',fullPage:true});
  await page.getByRole('button',{name:'Sign out'}).click();
  await expect(page.getByRole('region',{name:'Media library'})).toHaveCount(0);
  expect(errors).toEqual([]);
});
