import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import path from 'node:path';
import {tmpdir} from 'node:os';
import {once} from 'node:events';
import {generateKeyPairSync,createHash} from 'node:crypto';
import {AccessStore,FileAccessReader} from '../server/access-store.js';
import type {AccessService} from '../src/shared/access.js';
import {createApp} from '../server/app.js';
import {config} from '../server/config.js';
import {createImageApp,mediaErrorHandler} from '../server/media/app.js';
import {parseImageSsoConfig} from '../server/media/sso-auth.js';
import {readSsoClients} from '../server/sso-config.js';
const admin='111111111111111111',member='222222222222222222',other='333333333333333333';
const options=(revision:number,grants:AccessService[]=[],extra={})=>({expectedRevision:revision,displayName:'Test profile',active:true,admin:false,grants,...extra});
async function fixture(){
 const root=await fs.mkdtemp(path.join(tmpdir(),'dc-access-'));await fs.chmod(root,0o700);const directory=path.join(root,'access');await fs.mkdir(directory,{mode:0o700});
 const key=generateKeyPairSync('ed25519'),keyfile=path.join(root,'sign.pem');await fs.writeFile(keyfile,key.privateKey.export({type:'pkcs8',format:'pem'}),{mode:0o600});const secret='s'.repeat(43);let identity=admin;
 const clients=['image-service','servercontroller','proxymanager'].map((id,index)=>({id,clientSecret:String(index).repeat(43),callbackUrl:`https://${['img.dcrp.cz','admin.diamondcrew.net','proxy.diamondcrew.net'][index]}/auth/sso/callback`,startUrl:`https://${['img.dcrp.cz','admin.diamondcrew.net','proxy.diamondcrew.net'][index]}/auth/sso/start`,allowedDiscordIds:[]}));
 const c={...config,accessStoreDirectory:directory,staffAdminIds:[admin],accessBootstrapLegacy:false,production:false,sessionSecret:'test-session-secret',discordClientId:admin,discordClientSecret:'fixture',discordRedirectUri:'http://localhost/auth/discord/callback',discordAllowedIds:new Set([other]),ssoEnabled:true,ssoPrivateKeyFile:keyfile,ssoKeyId:'test',ssoClients:readSsoClients(JSON.stringify(clients))};
 const app=createApp('staff',c,async()=>new Response(JSON.stringify({id:identity,username:'profile',token_type:'Bearer',access_token:'fixture'})));const server=app.listen(0,'127.0.0.1');await once(server,'listening');const base=`http://127.0.0.1:${(server.address() as {port:number}).port}`;
 const login=async(id:string)=>{identity=id;const start=await fetch(base+'/auth/discord',{redirect:'manual'});const state=new URL(start.headers.get('location')!).searchParams.get('state');const end=await fetch(base+'/auth/discord/callback?code=fixture&state='+state,{redirect:'manual',headers:{Cookie:start.headers.getSetCookie()[0].split(';')[0]}});const cookie=end.headers.getSetCookie().find(v=>v.startsWith('dc_session='))?.split(';')[0]||'';const session=await(await fetch(base+'/api/session',{headers:{Cookie:cookie}})).json();return {cookie,csrf:session.csrfToken,session};};
 const signed=await login(admin),store=new AccessStore({directory,adminIds:[]});
 const update=(id:string,body:unknown,who=signed)=>fetch(base+'/api/admin/access/users/'+id,{method:'PUT',headers:{Cookie:who.cookie,'X-CSRF-Token':who.csrf||'','Content-Type':'application/json'},body:JSON.stringify(body)});
 return {root,directory,base,c,key,secret,store,signed,login,update,close:async()=>{await new Promise<void>(r=>server.close(()=>r()));await fs.rm(root,{recursive:true});}};
}
test('explicit bootstrap, opt-in legacy import and self/last-admin guards; missing store cannot silently reset access',async()=>{
 const root=await fs.mkdtemp(path.join(tmpdir(),'dc-access-bootstrap-'));await fs.chmod(root,0o700);
 try{assert.throws(()=>new AccessStore({directory:root,adminIds:[]}));const store=new AccessStore({directory:root,adminIds:[admin],legacy:new Map([[member,['image-service']]])});assert.equal(store.user(admin)?.admin,true);assert.deepEqual(store.user(admin)?.grants,[]);assert.equal(store.allowed(member,'image-service'),true);assert.equal(store.user(member)?.admin,false);const reopened=new AccessStore({directory:root,adminIds:[other]});assert.equal(reopened.user(other),undefined);assert.throws(()=>store.update(admin,admin,options(store.read().revision,[],{active:false,admin:true})),/own administrator/);assert.throws(()=>store.update(admin,admin,options(store.read().revision)),/own administrator/);await fs.unlink(path.join(root,'access.json'));assert.throws(()=>store.read());assert.throws(()=>new AccessStore({directory:root,adminIds:[admin]}));}finally{await fs.rm(root,{recursive:true});}
});
test('admin API rejects unauthorized/CSRF/invalid writes; concurrent revisions have one winner and durable actor audit',async()=>{
 const f=await fixture();try{assert.equal((await fetch(f.base+'/api/admin/access')).status,401);const ordinary=await f.login(other);assert.equal(ordinary.session.authenticated,true);assert.equal(ordinary.session.internalAccess,false);assert.equal(ordinary.session.adminAccess,false);assert.equal((await f.update(other,options(1,[],{admin:true}),ordinary)).status,403);assert.equal((await f.update(member,options(1),{...f.signed,csrf:''})).status,403);assert.equal((await f.update(member,{...options(1),unknown:'bad'})).status,400);assert.equal((await f.update(member,options(1,[],{displayName:'a'.repeat(9000)}))).status,413);
 const both=await Promise.all([f.update(member,options(1)),f.update(other,options(1))]);assert.deepEqual(both.map(r=>r.status).sort(),[200,409]);const snapshot=f.store.read();assert.equal(snapshot.revision,2);assert.equal(snapshot.audit.length,2);assert.equal(snapshot.audit[1].actor,admin);assert.equal(snapshot.audit[1].before,null);assert.deepEqual(snapshot.audit[1].after.grants,[]);assert.equal((await f.update(admin,options(2,[],{active:false,admin:true}))).status,409);assert.equal((await f.update(admin,options(2))).status,409);const history=await(await fetch(f.base+'/api/admin/access/audit?before=2',{headers:{Cookie:f.signed.cookie}})).json();assert.equal(history.entries.length,1);assert.equal(history.entries[0].action,'bootstrap');assert.equal((await fetch(f.base+'/api/admin/access/audit?before=bad',{headers:{Cookie:f.signed.cookie}})).status,400);
 }finally{await f.close();}
});
test('managed broker keeps exact deployed Controller/Proxy claims schema',async()=>{
 const f=await fixture();try{await f.update(member,options(f.store.read().revision,['servercontroller','proxymanager']));const user=await f.login(member),verifier='v'.repeat(43),state='t'.repeat(43),challenge=createHash('sha256').update(verifier).digest('base64url');for(const audience of ['servercontroller','proxymanager']){const issued=await fetch(`${f.base}/sso/${audience}?state=${state}&code_challenge=${challenge}`,{redirect:'manual',headers:{Cookie:user.cookie}});assert.equal(issued.status,303);const ticket=new URL(issued.headers.get('location')!).searchParams.get('ticket');const response=await fetch(f.base+'/sso/api/redeem',{method:'POST',headers:{'Content-Type':'application/json',Authorization:'Bearer '+f.c.ssoClients.find(c=>c.id===audience)!.clientSecret},body:JSON.stringify({audience,ticket,state,code_verifier:verifier})});assert.equal(response.status,200);const claims=JSON.parse(Buffer.from((await response.json()).assertion.split('.')[1],'base64url').toString());assert.deepEqual(Object.keys(claims).sort(),['iss','aud','sub','iat','exp','jti','state'].sort());assert.equal(claims.sub,member);}}finally{await f.close();}
});
test('shared managed grants revoke active Image sessions and pending tickets; regrant never revives old sessions',async()=>{
 const f=await fixture();let imageServer:ReturnType<ReturnType<typeof createApp>['listen']>|undefined;try{
 await f.update(member,options(f.store.read().revision,['image-service']));const user=await f.login(member);const mediaRoot=path.join(f.root,'media');await fs.mkdir(mediaRoot);const png=Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+/g0sAAAAASUVORK5CYII=','base64');await fs.writeFile(path.join(mediaRoot,'existing.png'),png);
 const imageConfig=parseImageSsoConfig({redeem_secret:f.c.ssoClients[0].clientSecret,verification_keys:{test:f.key.publicKey.export({type:'spki',format:'pem'})},allowed_ids:[]});const previous=process.env.IMAGE_ACCESS_STORE_DIRECTORY;process.env.IMAGE_ACCESS_STORE_DIRECTORY=f.directory;let image;try{image=await createImageApp({production:false},{root:mediaRoot,publicOrigin:'https://img.dcrp.cz',maxUploadBytes:1048576,maxBatchBytes:2097152,maxFiles:3,cacheSeconds:300},async(_url,init)=>fetch(f.base+'/sso/api/redeem',init),undefined,imageConfig);}finally{if(previous===undefined)delete process.env.IMAGE_ACCESS_STORE_DIRECTORY;else process.env.IMAGE_ACCESS_STORE_DIRECTORY=previous;}
 image.app.use(image.publicFiles);image.app.use(mediaErrorHandler);imageServer=image.app.listen(0,'127.0.0.1');await once(imageServer,'listening');const base=`http://127.0.0.1:${(imageServer.address() as {port:number}).port}`;
 const issue=async()=>{const start=await fetch(base+'/auth/sso/start',{redirect:'manual'});const url=new URL(start.headers.get('location')!);const grant=await fetch(f.base+url.pathname+url.search,{redirect:'manual',headers:{Cookie:user.cookie}});assert.equal(grant.status,303);return {url:new URL(grant.headers.get('location')!),cookie:start.headers.getSetCookie()[0].split(';')[0]};};const redeem=(flow:Awaited<ReturnType<typeof issue>>)=>fetch(base+flow.url.pathname+flow.url.search,{redirect:'manual',headers:{Cookie:flow.cookie}});
 const one=await redeem(await issue()),two=await redeem(await issue());assert.equal(one.status,303);assert.equal(two.status,303);const cookie=one.headers.getSetCookie().find(s=>s.startsWith('dci_image_session='))!.split(';')[0],untouched=two.headers.getSetCookie().find(s=>s.startsWith('dci_image_session='))!.split(';')[0];assert.equal((await fetch(base+'/api/media',{headers:{Cookie:cookie}})).status,200);const pending=await issue();await f.update(member,options(f.store.read().revision,[]));assert.equal((await fetch(base+'/api/media',{headers:{Cookie:cookie}})).status,401);assert.equal((await redeem(pending)).status,403);await f.update(member,options(f.store.read().revision,['image-service']));assert.equal((await fetch(base+'/api/media',{headers:{Cookie:untouched}})).status,401);assert.deepEqual(Buffer.from(await(await fetch(base+'/existing.png')).arrayBuffer()),png);
 const fresh=await f.login(member);await f.update(member,options(f.store.read().revision,['image-service'],{active:false}));assert.equal((await(await fetch(f.base+'/api/session',{headers:{Cookie:fresh.cookie}})).json()).authenticated,false);assert.equal((await f.login(member)).session.authenticated,false);
 }finally{if(imageServer)await new Promise<void>(r=>imageServer!.close(()=>r()));await f.close();}
});
test('corrupt managed store fails closed; public variant exposes no profiles and never reads managed store',async()=>{
 const f=await fixture();let server:ReturnType<ReturnType<typeof createApp>['listen']>|undefined;try{await fs.writeFile(path.join(f.directory,'access.json'),'{bad');assert.throws(()=>new FileAccessReader(f.directory).read());assert.equal((await fetch(f.base+'/api/admin/access',{headers:{Cookie:f.signed.cookie}})).status,503);assert.equal((await fetch(f.base+'/api/public/status')).status,200);const app=createApp('public',{...f.c,accessStoreDirectory:'/definitely/missing/private-store'});server=app.listen(0,'127.0.0.1');await once(server,'listening');const base=`http://127.0.0.1:${(server.address() as {port:number}).port}`;for(const route of ['/api/admin/access','/api/admin/access/audit','/api/session','/admin/access']){const response=await fetch(base+route);assert.equal(response.status,404);assert.equal((await response.text()).includes(admin),false);}const response=await fetch(base+'/api/public/status');assert.equal(response.status,200);assert.equal((await response.text()).includes(admin),false);}finally{if(server)await new Promise<void>(r=>server!.close(()=>r()));await f.close();}
});
