import type { Service } from "../shared/types.js";

// Launch availability is intentional and independent of monitoring health.
export const services: Service[] = [
  {
    id: "manager",
    name: "DiamondCrew Server Manager",
    description: "Your servers. One control plane.",
    url: "https://panel.diamondcrew.net",
    enabled: true,
    status: "OPERATIONAL",
    category: "management",
    icon: "panel",
  },
  {
    id: "cockpit",
    name: "Cockpit",
    description: "Host administration & system insights.",
    url: "https://admin.diamondcrew.net",
    enabled: false,
    status: "IN PROGRESS",
    category: "management",
    icon: "terminal",
  },
  {
    id: "proxy",
    name: "Proxy Manager",
    description: "Routing, domains & SSL certificates.",
    url: "https://proxy.diamondcrew.net",
    enabled: false,
    status: "IN PROGRESS",
    category: "management",
    icon: "network",
  },
  {
    id: "prismatic-prod",
    name: "Prismatic PROD txAdmin",
    description: "Production roleplay environment.",
    url: "https://tx.pmrp.cz",
    enabled: false,
    status: "IN PROGRESS",
    category: "roleplay",
    icon: "game",
    project: "Prismatic",
    environment: "PROD",
  },
  {
    id: "prismatic-dev",
    name: "Prismatic DEV txAdmin",
    description: "Development & testing environment.",
    url: "https://tx-dev.pmrp.cz",
    enabled: false,
    status: "IN PROGRESS",
    category: "roleplay",
    icon: "game",
    project: "Prismatic",
    environment: "DEV",
  },
  {
    id: "diamond-prod",
    name: "DiamondCrew PROD txAdmin",
    description: "Production roleplay environment.",
    url: "https://tx.dcrp.cz",
    enabled: false,
    status: "IN PROGRESS",
    category: "roleplay",
    icon: "game",
    project: "DiamondCrew",
    environment: "PROD",
  },
  {
    id: "diamond-dev",
    name: "DiamondCrew DEV txAdmin",
    description: "Development & testing environment.",
    url: "https://tx-dev.dcrp.cz",
    enabled: false,
    status: "IN PROGRESS",
    category: "roleplay",
    icon: "game",
    project: "DiamondCrew",
    environment: "DEV",
  },
];
