import {useEffect,useState} from 'react';
import type {AccessView,AccessUser,AccessService,AccessChange} from '../shared/access';
import './AccessAdmin.css';
const labels:Record<AccessService,string>={cookbook:'Cookbook',servercontroller:'Server Controller — centrální SSO',proxymanager:'Proxy Manager — centrální SSO','image-service':'Image Service — správa médií'};
const blank=():AccessUser=>({id:'',displayName:'',active:true,admin:false,grants:[],epoch:1});
export function AccessAdmin({csrf,onExpired}:{csrf:string;onExpired:()=>unknown}){
 const [data,setData]=useState<AccessView>(),[selected,setSelected]=useState<AccessUser>(blank),[creating,setCreating]=useState(true),[formRevision,setFormRevision]=useState<number>(),[filter,setFilter]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[audit,setAudit]=useState<AccessChange[]>([]),[more,setMore]=useState(true);
 async function request(url:string,options?:RequestInit){const response=await fetch(url,options);if(response.status===401||response.status===403){onExpired();throw Error('Přístup ke správě není dostupný. Přihlas se znovu.');}let body;try{body=await response.json();}catch{throw Error('Správa přístupů není dostupná.');}if(!response.ok)throw Error(response.status===409?'Údaje se změnily nebo by změna zablokovala správce. Obnov seznam a zkontroluj změnu.':response.status===429?'Příliš mnoho požadavků. Zkus to za chvíli.':body.error||'Požadavek se nezdařil.');return body;}
 async function load(){setBusy(true);setError('');try{const result:AccessView=await request('/api/admin/access');setData(result);setSelected(blank());setCreating(true);setFormRevision(result.revision);setAudit(result.audit);setMore(result.audit.length===100);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 useEffect(()=>{void load();},[]);
 async function save(event:React.FormEvent){event.preventDefault();if(!data||busy||formRevision===undefined||duplicate)return;setBusy(true);setError('');setNotice('');try{await request('/api/admin/access/users/'+encodeURIComponent(selected.id),{method:'PUT',headers:{'Content-Type':'application/json','X-CSRF-Token':csrf},body:JSON.stringify({expectedRevision:formRevision,displayName:selected.displayName,active:selected.active,admin:selected.admin,grants:selected.grants})});setNotice('Profil a přístupy byly uloženy. Změny jsou zaznamenané v auditu.');await load();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 function choose(user?:AccessUser){if(busy)return;setFormRevision(data?.revision);setSelected(user?{...user,grants:[...user.grants]}:blank());setCreating(!user);setError('');setNotice('');}
 async function older(){if(!audit.length)return;setBusy(true);try{const result=await request('/api/admin/access/audit?before='+audit[audit.length-1].revision);setAudit(current=>[...current,...result.entries]);setMore(result.entries.length===100);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 const self=selected.id===data?.actorId;
 const duplicate=creating&&!!data?.users.some(user=>user.id===selected.id);
 return <section className="access-admin" aria-labelledby="access-title"><header><h1 id="access-title">Uživatelé a přístupy</h1><p>Správa profilů podle Discord ID. Nevytváří Discord účty ani hesla.</p></header>
 <div className="access-info">Přístup ke správě médií umožňuje prohlížet a měnit média. Odebrání přístupu nebo zablokování zneplatní přihlášení ke správě médií. Controller a Proxy navíc vyžadují připravený účet propojený s Discordem; jejich již otevřená přihlášení mají vlastní pravidla odhlášení. Panel a txAdmin mají vlastní přihlášení a oprávnění.</div>
 {error&&<p className="access-error" role="alert">{error}</p>}{notice&&<p role="status">{notice}</p>}
 <div className="access-toolbar"><label>Najít profil<input value={filter} onChange={e=>setFilter(e.target.value)} placeholder="Discord ID nebo název"/></label><button className="button subtle" onClick={()=>void load()} disabled={busy}>Obnovit a zahodit formulář</button><button className="button" onClick={()=>choose()} disabled={busy}>Nový profil</button></div>
 {!data?<p role="status">{error?'Data nelze načíst.':'Načítání přístupů…'}</p>:<div className="access-layout"><div className="access-users" aria-label="Profily">{data.users.filter(u=>(u.id+' '+u.displayName).toLocaleLowerCase().includes(filter.toLocaleLowerCase())).map(user=><button key={user.id} className={selected.id===user.id?'selected':''} disabled={busy} onClick={()=>choose(user)}><strong>{user.displayName||user.id}</strong><small>{user.id}</small><span>{user.active?'Aktivní':'Zablokovaný'}{user.admin?' · Správce Staff':''}</span></button>)}{!data.users.length&&<p>Žádné profily.</p>}</div>
 <form onSubmit={save} className="access-form"><h2>{creating?'Nový profil':'Upravit profil'}</h2><label>Discord User ID<input required pattern="[0-9]{17,20}" inputMode="numeric" value={selected.id} disabled={!creating||busy} onChange={e=>setSelected({...selected,id:e.target.value})}/></label><label>Název profilu<input maxLength={80} value={selected.displayName} disabled={busy} onChange={e=>setSelected({...selected,displayName:e.target.value})}/></label><label className="access-check"><input type="checkbox" checked={selected.active} disabled={busy||self} onChange={e=>setSelected({...selected,active:e.target.checked})}/>Profil je aktivní</label><label className="access-check"><input type="checkbox" checked={selected.admin} disabled={busy||self} onChange={e=>setSelected({...selected,admin:e.target.checked})}/>Správce uživatelů a přístupů ve Staff</label><fieldset disabled={busy}><legend>Výslovně povolené služby</legend>{data.services.map(service=><label className="access-check" key={service}><input type="checkbox" checked={selected.grants.includes(service)} onChange={e=>setSelected({...selected,grants:e.target.checked?[...selected.grants,service]:selected.grants.filter(g=>g!==service)})}/>{labels[service]}</label>)}</fieldset>{creating&&<p>Nový profil nemá žádné služby povolené, dokud je výslovně nevybereš.</p>}{self&&<p>Vlastní profil nelze zablokovat ani zbavit správy. Změna vlastních služeb může vyžadovat nové přihlášení.</p>}{duplicate&&<p role="alert">Tento Discord ID už má profil. Vyber jej v seznamu a uprav existující profil.</p>}<button type="submit" className="button" disabled={busy||!selected.id||duplicate}>{busy?'Ukládání…':'Uložit profil a přístupy'}</button></form></div>}
 <section className="access-audit" aria-labelledby="audit-title"><h2 id="audit-title">Audit změn</h2><p>Záznamy obsahují původní a nové nastavení. Bootstrap označuje jednorázové zavedení privátní konfigurace.</p>{audit.map(entry=><details key={entry.revision}><summary><time dateTime={entry.at}>{new Date(entry.at).toLocaleString('cs-CZ')}</time> · {entry.actor} · {entry.action==='create'?'nový profil':entry.action==='bootstrap'?'bootstrap':'změna'} · {entry.subject}</summary><div><strong>Před změnou</strong><pre>{entry.before?JSON.stringify(entry.before,null,2):'Profil neexistoval'}</pre><strong>Po změně</strong><pre>{JSON.stringify(entry.after,null,2)}</pre></div></details>)}{more&&audit.length>0&&<button className="button subtle" disabled={busy} onClick={()=>void older()}>Starší záznamy</button>}</section></section>;
}
